sudo: required
language: android
jdk: oraclejdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
  global:
  - ANDROID_API_LEVEL=29
  - EMULATOR_API_LEVEL=22
  - ANDROID_BUILD_TOOLS_VERSION=29.0.2
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=20 # minutes
  - QEMU_AUDIO_DRV=none

android:
  components:
  - tools
  - platform-tools
  - tools # same line as first one but allows to get the newest Android SDK tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL # SDK version used to compile the project
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository # play services and firebase repository
  - extra-android-m2repository # android support library repository

  - addon-google_apis-google-$ANDROID_API_LEVEL
  - addon-google_apis-google-$EMULATOR_API_LEVEL

  - sys-img-$ANDROID_ABI-addon-google_apis-google-$EMULATOR_API_LEVEL # system image used by emulator
  - sys-img-$ANDROID_ABI-google_apis-$EMULATOR_API_LEVEL

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window -engine classic &


  - adb shell input keyevent 82 &

script:
  - ./gradlew clean check -Pbuild=CI